openapi: 3.0.2
info:
  contact:
    name: '#data-product-dev'
    url: https://xendit.slack.com/archives/CA97LL668
  description: XENDIT SDK openapi spec
  license:
    name: No License
    url: https://choosealicense.com/no-permission/
  title: XENDIT SDK openapi spec
  version: 1.0.0
servers:
- description: Xendit API Server
  url: https://api.xendit.co
paths:
  /customers:
    get:
      description: "Retrieves an array with a customer object that matches the provided\
        \ reference_id - the identifier provided by you For detail explanations, see\
        \ this link: https://developers.xendit.co/api-reference/#get-customer-by-reference-id"
      operationId: getCustomerByReferenceID
      parameters:
      - description: Merchant's reference of end customer
        explode: true
        in: query
        name: reference_id
        required: true
        schema:
          maxLength: 255
          type: string
        style: form
      - description: The sub-account user-id that you want to make this transaction
          for.
        explode: false
        in: header
        name: for-user-id
        required: false
        schema:
          example: user-1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCustomerByReferenceID_200_response'
          description: End Customers
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCustomerByReferenceID_400_response'
          description: Various errors
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: GET customers by reference id
      tags:
      - customer
    post:
      description: "Function to create a customer that you may use in your Invoice\
        \ or Payment Requests. For detail explanations, see this link: https://developers.xendit.co/api-reference/#create-customer"
      operationId: createCustomer
      parameters:
      - description: A unique key to prevent processing duplicate requests.
        explode: false
        in: header
        name: idempotency-key
        required: false
        schema:
          example: idempotency-123
          type: string
        style: simple
      - description: The sub-account user-id that you want to make this transaction
          for.
        explode: false
        in: header
        name: for-user-id
        required: false
        schema:
          example: user-1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
        description: Request object for end customer object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: Created End Customer
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createCustomer_400_response'
          description: Various errors
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: Create Customer
      tags:
      - customer
  /customers/{id}:
    get:
      description: "Retrieves a single customer object For detail explanations, see\
        \ this link: https://developers.xendit.co/api-reference/#get-customer"
      operationId: getCustomer
      parameters:
      - description: End customer resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          format: uuid
          type: string
        style: simple
      - description: The sub-account user-id that you want to make this transaction
          for.
        explode: false
        in: header
        name: for-user-id
        required: false
        schema:
          example: user-1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: End Customer Resource
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCustomerByReferenceID_400_response'
          description: Various errors
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDataNotFound'
          description: Customer not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: Get Customer By ID
      tags:
      - customer
    patch:
      description: "Function to update an existing customer. For a detailed explanation\
        \ For detail explanations, see this link: https://developers.xendit.co/api-reference/#update-customer"
      operationId: updateCustomer
      parameters:
      - description: End customer resource id
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          format: uuid
          type: string
        style: simple
      - description: The sub-account user-id that you want to make this transaction
          for.
        explode: false
        in: header
        name: for-user-id
        required: false
        schema:
          example: user-1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchCustomer'
        description: Update Request for end customer object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: Updated End Customer
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateCustomer_400_response'
          description: Various errors
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error
      summary: Update End Customer Resource
      tags:
      - customer
components:
  schemas:
    Error:
      properties:
        error_code:
          example: SERVER_ERROR
          type: string
        message:
          example: "Something unexpected happened, we are investigating this issue\
            \ right now"
          type: string
        errors:
          items:
            type: object
          type: array
      required:
      - error_code
      - message
      type: object
    CountryCode:
      description: ISO3166-2 country code
      example: ID
      maxLength: 2
      nullable: true
      type: string
    EmploymentDetail:
      example:
        nature_of_business: nature_of_business
        employer_name: employer_name
        role_description: role_description
      nullable: true
      properties:
        employer_name:
          description: Name of employer
          nullable: true
          type: string
        nature_of_business:
          description: Industry or nature of business
          nullable: true
          type: string
        role_description:
          description: Occupation or title
          nullable: true
          type: string
      type: object
    IndividualDetail:
      example:
        place_of_birth: place_of_birth
        gender: MALE
        nationality: ID
        surname: surname
        date_of_birth: 2017-07-21
        surname_non_roman: surname_non_roman
        employment:
          nature_of_business: nature_of_business
          employer_name: employer_name
          role_description: role_description
        given_names: given_names
        given_names_non_roman: given_names_non_roman
        middle_name: middle_name
        mother_maiden_name: mother_maiden_name
      nullable: true
      properties:
        given_names:
          maxLength: 255
          type: string
        given_names_non_roman:
          maxLength: 255
          nullable: true
          type: string
        middle_name:
          maxLength: 255
          nullable: true
          type: string
        surname:
          maxLength: 255
          nullable: true
          type: string
        surname_non_roman:
          maxLength: 255
          nullable: true
          type: string
        mother_maiden_name:
          maxLength: 255
          nullable: true
          type: string
        gender:
          enum:
          - MALE
          - FEMALE
          - OTHER
          nullable: true
          type: string
        date_of_birth:
          example: 2017-07-21
          maxLength: 30
          nullable: true
          type: string
        nationality:
          description: ISO3166-2 country code
          example: ID
          maxLength: 2
          nullable: true
          type: string
        place_of_birth:
          maxLength: 255
          nullable: true
          type: string
        employment:
          $ref: '#/components/schemas/EmploymentDetail'
      type: object
    BusinessDetail:
      example:
        business_name: business_name
        nature_of_business: nature_of_business
        business_type: CORPORATION
        date_of_registration: 2017-07-21
        business_domicile: ID
      nullable: true
      properties:
        business_name:
          maxLength: 255
          type: string
        business_type:
          enum:
          - CORPORATION
          - SOLE_PROPRIETOR
          - PARTNERSHIP
          - COOPERATIVE
          - TRUST
          - NON_PROFIT
          - GOVERNMENT
          nullable: true
          type: string
        date_of_registration:
          example: 2017-07-21
          maxLength: 10
          nullable: true
          type: string
        nature_of_business:
          maxLength: 255
          nullable: true
          type: string
        business_domicile:
          description: ISO3166-2 country code
          example: ID
          maxLength: 2
          nullable: true
          type: string
      type: object
    AddressStatus:
      enum:
      - ACTIVE
      - DELETED
      nullable: true
      type: string
    Address:
      example:
        country: ""
        is_primary: true
        city: city
        created: 2016-08-29T09:12:33.001Z
        province_state: province_state
        street_line2: street_line2
        street_line1: street_line1
        meta: "{}"
        id: d290f1ee-6c54-4b01-90e6-d701748f0851
        category: category
        postal_code: postal_code
        updated: 2016-08-29T09:12:33.001Z
        status: null
      properties:
        id:
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          format: uuid
          type: string
        category:
          maxLength: 255
          nullable: true
          type: string
        country:
          allOf:
          - $ref: '#/components/schemas/CountryCode'
          - nullable: true
        province_state:
          nullable: true
          type: string
        city:
          nullable: true
          type: string
        postal_code:
          nullable: true
          type: string
        street_line1:
          nullable: true
          type: string
        street_line2:
          nullable: true
          type: string
        status:
          $ref: '#/components/schemas/AddressStatus'
        is_primary:
          nullable: true
          type: boolean
        meta:
          nullable: true
          type: object
        created:
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
        updated:
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
      required:
      - category
      - city
      - country
      - is_primary
      - postal_code
      - province_state
      - street_line1
      - street_line2
      type: object
    Currency:
      description: "Primary currency of the account, if relevant. ISO 4217 Currency\
        \ Code"
      example: IDR
      type: string
    AccountBank:
      properties:
        account_number:
          description: Unique account identifier as per the bank records.
          type: string
        account_holder_name:
          description: Name of account holder as per the bank records. Needs to match
            the registered account name exactly. .
          nullable: true
          type: string
        swift_code:
          description: The SWIFT code for international payments
          nullable: true
          type: string
        account_type:
          description: "Free text account type, e.g., Savings, Transaction, Virtual\
            \ Account."
          nullable: true
          type: string
        account_details:
          description: "Potentially masked account detail, for display purposes only."
          nullable: true
          type: string
        currency:
          allOf:
          - $ref: '#/components/schemas/Currency'
          - nullable: true
      type: object
    AccountEwallet:
      properties:
        account_number:
          description: Unique account identifier as per the bank records.
          type: string
        account_holder_name:
          description: Name of account holder as per the bank records. Needs to match
            the registered account name exactly.
          nullable: true
          type: string
        currency:
          allOf:
          - $ref: '#/components/schemas/Currency'
          - nullable: true
      type: object
    AccountCard:
      properties:
        token_id:
          description: The token id returned in tokenisation
          type: string
      type: object
    AccountOTC:
      properties:
        payment_code:
          description: Complete fixed payment code (including prefix)
          type: string
        expires_at:
          description: YYYY-MM-DD string with expiry date for the payment code
          nullable: true
          type: string
      type: object
    AccountQRCode:
      properties:
        qr_string:
          description: String representation of the QR Code image
          type: string
      type: object
    AccountPayLater:
      properties:
        account_id:
          description: Alphanumeric string identifying this account. Usually an email
            address or phone number.
          type: string
        account_holder_name:
          description: Name of account holder as per the cardless credit account.
          nullable: true
          type: string
        currency:
          allOf:
          - $ref: '#/components/schemas/Currency'
          - nullable: true
      type: object
    IdentityAccountResponse:
      example:
        country: ID
        code: code
        created: 2016-08-29T09:12:33.001Z
        description: description
        company: company
        id: d290f1ee-6c54-4b01-90e6-d701748f0851
        type: BANK_ACCOUNT
        properties: null
        holder_name: holder_name
      properties:
        id:
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          format: uuid
          type: string
        code:
          nullable: true
          type: string
        company:
          nullable: true
          type: string
        description:
          nullable: true
          type: string
        country:
          description: ISO3166-2 country code
          example: ID
          maxLength: 2
          nullable: true
          type: string
        holder_name:
          nullable: true
          type: string
        type:
          enum:
          - BANK_ACCOUNT
          - EWALLET
          - CREDIT_CARD
          - OTC
          - QR_CODE
          - CARDLESS_CREDIT
          nullable: true
          type: string
        properties:
          $ref: '#/components/schemas/IdentityAccountResponse_properties'
        created:
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
      required:
      - company
      - country
      - description
      - properties
      - type
      type: object
    KYCDocumentType:
      enum:
      - BIRTH_CERTIFICATE
      - BANK_STATEMENT
      - DRIVING_LICENSE
      - IDENTITY_CARD
      - PASSPORT
      - VISA
      - BUSINESS_REGISTRATION
      - BUSINESS_LICENSE
      type: string
    KYCDocumentSubType:
      enum:
      - NATIONAL_ID
      - CONSULAR_ID
      - VOTER_ID
      - POSTAL_ID
      - RESIDENCE_PERMIT
      - TAX_ID
      - STUDENT_ID
      - MILITARY_ID
      - MEDICAL_ID
      - OTHERS
      nullable: true
      type: string
    KYCDocumentResponse:
      example:
        country: ""
        document_name: document_name
        document_number: document_number
        expires_at: expires_at
        sub_type: ""
        type: ""
        document_images:
        - document_images
        - document_images
        holder_name: holder_name
      properties:
        country:
          allOf:
          - $ref: '#/components/schemas/CountryCode'
          - nullable: true
        type:
          allOf:
          - $ref: '#/components/schemas/KYCDocumentType'
          - nullable: true
        sub_type:
          allOf:
          - $ref: '#/components/schemas/KYCDocumentSubType'
          - nullable: true
        document_name:
          nullable: true
          type: string
        document_number:
          nullable: true
          type: string
        expires_at:
          nullable: true
          type: string
        holder_name:
          nullable: true
          type: string
        document_images:
          items:
            type: string
          nullable: true
          type: array
      required:
      - country
      - document_images
      - document_name
      - document_number
      - expires_at
      - holder_name
      - sub_type
      - type
      type: object
    EndCustomerStatus:
      enum:
      - ACTIVE
      - INACTIVE
      - PENDING
      - BLOCKED
      - DELETED
      nullable: true
      type: string
    Customer:
      example:
        individual_detail:
          place_of_birth: place_of_birth
          gender: MALE
          nationality: ID
          surname: surname
          date_of_birth: 2017-07-21
          surname_non_roman: surname_non_roman
          employment:
            nature_of_business: nature_of_business
            employer_name: employer_name
            role_description: role_description
          given_names: given_names
          given_names_non_roman: given_names_non_roman
          middle_name: middle_name
          mother_maiden_name: mother_maiden_name
        business_detail:
          business_name: business_name
          nature_of_business: nature_of_business
          business_type: CORPORATION
          date_of_registration: 2017-07-21
          business_domicile: ID
        addresses:
        - country: ""
          is_primary: true
          city: city
          created: 2016-08-29T09:12:33.001Z
          province_state: province_state
          street_line2: street_line2
          street_line1: street_line1
          meta: "{}"
          id: d290f1ee-6c54-4b01-90e6-d701748f0851
          category: category
          postal_code: postal_code
          updated: 2016-08-29T09:12:33.001Z
          status: null
        - country: ""
          is_primary: true
          city: city
          created: 2016-08-29T09:12:33.001Z
          province_state: province_state
          street_line2: street_line2
          street_line1: street_line1
          meta: "{}"
          id: d290f1ee-6c54-4b01-90e6-d701748f0851
          category: category
          postal_code: postal_code
          updated: 2016-08-29T09:12:33.001Z
          status: null
        metadata: "{}"
        reference_id: reference_id
        kyc_documents:
        - country: ""
          document_name: document_name
          document_number: document_number
          expires_at: expires_at
          sub_type: ""
          type: ""
          document_images:
          - document_images
          - document_images
          holder_name: holder_name
        - country: ""
          document_name: document_name
          document_number: document_number
          expires_at: expires_at
          sub_type: ""
          type: ""
          document_images:
          - document_images
          - document_images
          holder_name: holder_name
        created: 2016-08-29T09:12:33.001Z
        description: description
        type: INDIVIDUAL
        phone_number: +6281295412345
        id: id
        mobile_number: +6281295412345
        identity_accounts:
        - country: ID
          code: code
          created: 2016-08-29T09:12:33.001Z
          description: description
          company: company
          id: d290f1ee-6c54-4b01-90e6-d701748f0851
          type: BANK_ACCOUNT
          properties: null
          holder_name: holder_name
        - country: ID
          code: code
          created: 2016-08-29T09:12:33.001Z
          description: description
          company: company
          id: d290f1ee-6c54-4b01-90e6-d701748f0851
          type: BANK_ACCOUNT
          properties: null
          holder_name: holder_name
        updated: 2016-08-29T09:12:33.001Z
        email: info@xendit.co
        status: null
      properties:
        type:
          default: INDIVIDUAL
          enum:
          - INDIVIDUAL
          - BUSINESS
          type: string
        reference_id:
          description: "Merchant's reference of this end customer, eg Merchant's user's\
            \ id. Must be unique."
          maxLength: 255
          type: string
        individual_detail:
          $ref: '#/components/schemas/IndividualDetail'
        business_detail:
          $ref: '#/components/schemas/BusinessDetail'
        description:
          maxLength: 1000
          nullable: true
          type: string
        email:
          example: info@xendit.co
          format: email
          nullable: true
          type: string
        mobile_number:
          example: +6281295412345
          format: E164
          nullable: true
          type: string
        phone_number:
          example: +6281295412345
          format: E164
          nullable: true
          type: string
        addresses:
          items:
            $ref: '#/components/schemas/Address'
          nullable: true
          type: array
        identity_accounts:
          items:
            $ref: '#/components/schemas/IdentityAccountResponse'
          nullable: true
          type: array
        kyc_documents:
          items:
            $ref: '#/components/schemas/KYCDocumentResponse'
          nullable: true
          type: array
        metadata:
          nullable: true
          type: object
        status:
          $ref: '#/components/schemas/EndCustomerStatus'
        id:
          type: string
        created:
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
        updated:
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
      required:
      - addresses
      - business_detail
      - created
      - description
      - email
      - id
      - identity_accounts
      - individual_detail
      - kyc_documents
      - metadata
      - mobile_number
      - phone_number
      - reference_id
      - type
      - updated
      type: object
    AddressRequest:
      example:
        line_1: line_1
        country_code: ID
        line_2: line_2
        is_primary: false
        city: city
        province_state: province_state
        suburb: suburb
        category: category
        postal_code: postal_code
        status: null
      properties:
        category:
          description: "Home, work or provincial"
          maxLength: 255
          type: string
        country_code:
          description: ISO3166-2 country code
          example: ID
          maxLength: 2
          nullable: true
          type: string
        province_state:
          type: string
        city:
          type: string
        suburb:
          type: string
        postal_code:
          type: string
        line_1:
          type: string
        line_2:
          type: string
        status:
          $ref: '#/components/schemas/AddressStatus'
        is_primary:
          default: false
          type: boolean
      type: object
    IdentityAccountType:
      enum:
      - BANK_ACCOUNT
      - EWALLET
      - CREDIT_CARD
      - PAY_LATER
      - OTC
      - QR_CODE
      type: string
    IdentityAccountRequest:
      example:
        country: ID
        description: description
        company: company
        type: null
        properties: null
      properties:
        type:
          $ref: '#/components/schemas/IdentityAccountType'
        company:
          description: "The issuing institution associated with the account (e.g.,\
            \ OCBC, GOPAY, 7-11). If adding financial accounts that Xendit supports,\
            \ we recommend you use the channel_name found at https://xendit.github.io/apireference/#payment-channels\
            \ for this field"
          maxLength: 100
          type: string
        description:
          description: Free text description of this account
          maxLength: 255
          type: string
        country:
          description: ISO3166-2 country code
          example: ID
          maxLength: 2
          nullable: true
          type: string
        properties:
          $ref: '#/components/schemas/IdentityAccountRequest_properties'
      type: object
    KYCDocumentRequest:
      example:
        country: ID
        document_name: KTP
        document_number: AA123467890
        expires_at: 2017-07-21
        sub_type: null
        type: null
        document_images:
        - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
        - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
        holder_name: John Doe
      properties:
        country:
          description: ISO3166-2 country code
          example: ID
          maxLength: 2
          nullable: true
          type: string
        type:
          $ref: '#/components/schemas/KYCDocumentType'
        sub_type:
          $ref: '#/components/schemas/KYCDocumentSubType'
        document_name:
          example: KTP
          type: string
        document_number:
          example: AA123467890
          type: string
        expires_at:
          example: 2017-07-21
          type: string
        holder_name:
          example: John Doe
          type: string
        document_images:
          items:
            description: pointer to file stored in xendit s3
            example: /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
            type: string
          type: array
      type: object
    CustomerRequest:
      example:
        individual_detail:
          place_of_birth: place_of_birth
          gender: MALE
          nationality: ID
          surname: surname
          date_of_birth: 2017-07-21
          surname_non_roman: surname_non_roman
          employment:
            nature_of_business: nature_of_business
            employer_name: employer_name
            role_description: role_description
          given_names: given_names
          given_names_non_roman: given_names_non_roman
          middle_name: middle_name
          mother_maiden_name: mother_maiden_name
        business_detail:
          business_name: business_name
          nature_of_business: nature_of_business
          business_type: CORPORATION
          date_of_registration: 2017-07-21
          business_domicile: ID
        addresses:
        - line_1: line_1
          country_code: ID
          line_2: line_2
          is_primary: false
          city: city
          province_state: province_state
          suburb: suburb
          category: category
          postal_code: postal_code
          status: null
        - line_1: line_1
          country_code: ID
          line_2: line_2
          is_primary: false
          city: city
          province_state: province_state
          suburb: suburb
          category: category
          postal_code: postal_code
          status: null
        metadata: "{}"
        reference_id: reference_id
        kyc_documents:
        - country: ID
          document_name: KTP
          document_number: AA123467890
          expires_at: 2017-07-21
          sub_type: null
          type: null
          document_images:
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          holder_name: John Doe
        - country: ID
          document_name: KTP
          document_number: AA123467890
          expires_at: 2017-07-21
          sub_type: null
          type: null
          document_images:
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          holder_name: John Doe
        description: description
        type: INDIVIDUAL
        phone_number: +6281295412345
        mobile_number: +6281295412345
        client_name: AirAsia Indonesia
        identity_accounts:
        - country: ID
          description: description
          company: company
          type: null
          properties: null
        - country: ID
          description: description
          company: company
          type: null
          properties: null
        email: info@xendit.co
      properties:
        client_name:
          description: Entity's name for this client
          example: AirAsia Indonesia
          type: string
        reference_id:
          description: "Merchant's reference of this end customer, eg Merchant's user's\
            \ id. Must be unique."
          maxLength: 255
          type: string
        type:
          default: INDIVIDUAL
          enum:
          - INDIVIDUAL
          - BUSINESS
          type: string
        individual_detail:
          $ref: '#/components/schemas/IndividualDetail'
        business_detail:
          $ref: '#/components/schemas/BusinessDetail'
        description:
          maxLength: 1000
          nullable: true
          type: string
        email:
          example: info@xendit.co
          format: email
          type: string
        mobile_number:
          example: +6281295412345
          format: E164
          type: string
        phone_number:
          example: +6281295412345
          format: E164
          type: string
        addresses:
          items:
            $ref: '#/components/schemas/AddressRequest'
          type: array
        identity_accounts:
          items:
            $ref: '#/components/schemas/IdentityAccountRequest'
          type: array
        kyc_documents:
          items:
            $ref: '#/components/schemas/KYCDocumentRequest'
          type: array
        metadata:
          type: object
      required:
      - client
      - entity
      - reference_id
      type: object
    ResponseDataNotFound:
      properties:
        error_code:
          enum:
          - DATA_NOT_FOUND
          - ENTITY_NOT_FOUND_ERROR
          - CLIENT_NOT_FOUND_ERROR
          example: DATA_NOT_FOUND
          type: string
        message:
          example: Provided customer_id does not exist
      type: object
    PatchCustomer:
      example:
        individual_detail:
          place_of_birth: place_of_birth
          gender: MALE
          nationality: ID
          surname: surname
          date_of_birth: 2017-07-21
          surname_non_roman: surname_non_roman
          employment:
            nature_of_business: nature_of_business
            employer_name: employer_name
            role_description: role_description
          given_names: given_names
          given_names_non_roman: given_names_non_roman
          middle_name: middle_name
          mother_maiden_name: mother_maiden_name
        business_detail:
          business_name: business_name
          nature_of_business: nature_of_business
          business_type: CORPORATION
          date_of_registration: 2017-07-21
          business_domicile: ID
        metadata: "{}"
        addresses:
        - line_1: line_1
          country_code: ID
          line_2: line_2
          is_primary: false
          city: city
          province_state: province_state
          suburb: suburb
          category: category
          postal_code: postal_code
          status: null
        - line_1: line_1
          country_code: ID
          line_2: line_2
          is_primary: false
          city: city
          province_state: province_state
          suburb: suburb
          category: category
          postal_code: postal_code
          status: null
        reference_id: reference_id
        kyc_documents:
        - country: ID
          document_name: KTP
          document_number: AA123467890
          expires_at: 2017-07-21
          sub_type: null
          type: null
          document_images:
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          holder_name: John Doe
        - country: ID
          document_name: KTP
          document_number: AA123467890
          expires_at: 2017-07-21
          sub_type: null
          type: null
          document_images:
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          - /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwc=
          holder_name: John Doe
        description: description
        phone_number: +6281295412345
        mobile_number: +6281295412345
        client_name: AirAsia Indonesia
        identity_accounts:
        - country: ID
          description: description
          company: company
          type: null
          properties: null
        - country: ID
          description: description
          company: company
          type: null
          properties: null
        email: info@xendit.co
        status: null
      properties:
        client_name:
          description: Entity's name for this client
          example: AirAsia Indonesia
          nullable: true
          type: string
        reference_id:
          description: "Merchant's reference of this end customer, eg Merchant's user's\
            \ id. Must be unique."
          maxLength: 255
          nullable: true
          type: string
        individual_detail:
          $ref: '#/components/schemas/IndividualDetail'
        business_detail:
          $ref: '#/components/schemas/BusinessDetail'
        description:
          maxLength: 1000
          nullable: true
          type: string
        email:
          example: info@xendit.co
          format: email
          nullable: true
          type: string
        mobile_number:
          example: +6281295412345
          format: E164
          nullable: true
          type: string
        phone_number:
          example: +6281295412345
          format: E164
          nullable: true
          type: string
        metadata:
          nullable: true
          type: object
        addresses:
          items:
            $ref: '#/components/schemas/AddressRequest'
          nullable: true
          type: array
        identity_accounts:
          items:
            $ref: '#/components/schemas/IdentityAccountRequest'
          nullable: true
          type: array
        kyc_documents:
          items:
            $ref: '#/components/schemas/KYCDocumentRequest'
          nullable: true
          type: array
        status:
          $ref: '#/components/schemas/EndCustomerStatus'
      required:
      - client
      - entity
      type: object
    getCustomerByReferenceID_200_response:
      example:
        data:
        - individual_detail:
            place_of_birth: place_of_birth
            gender: MALE
            nationality: ID
            surname: surname
            date_of_birth: 2017-07-21
            surname_non_roman: surname_non_roman
            employment:
              nature_of_business: nature_of_business
              employer_name: employer_name
              role_description: role_description
            given_names: given_names
            given_names_non_roman: given_names_non_roman
            middle_name: middle_name
            mother_maiden_name: mother_maiden_name
          business_detail:
            business_name: business_name
            nature_of_business: nature_of_business
            business_type: CORPORATION
            date_of_registration: 2017-07-21
            business_domicile: ID
          addresses:
          - country: ""
            is_primary: true
            city: city
            created: 2016-08-29T09:12:33.001Z
            province_state: province_state
            street_line2: street_line2
            street_line1: street_line1
            meta: "{}"
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            category: category
            postal_code: postal_code
            updated: 2016-08-29T09:12:33.001Z
            status: null
          - country: ""
            is_primary: true
            city: city
            created: 2016-08-29T09:12:33.001Z
            province_state: province_state
            street_line2: street_line2
            street_line1: street_line1
            meta: "{}"
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            category: category
            postal_code: postal_code
            updated: 2016-08-29T09:12:33.001Z
            status: null
          metadata: "{}"
          reference_id: reference_id
          kyc_documents:
          - country: ""
            document_name: document_name
            document_number: document_number
            expires_at: expires_at
            sub_type: ""
            type: ""
            document_images:
            - document_images
            - document_images
            holder_name: holder_name
          - country: ""
            document_name: document_name
            document_number: document_number
            expires_at: expires_at
            sub_type: ""
            type: ""
            document_images:
            - document_images
            - document_images
            holder_name: holder_name
          created: 2016-08-29T09:12:33.001Z
          description: description
          type: INDIVIDUAL
          phone_number: +6281295412345
          id: id
          mobile_number: +6281295412345
          identity_accounts:
          - country: ID
            code: code
            created: 2016-08-29T09:12:33.001Z
            description: description
            company: company
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            type: BANK_ACCOUNT
            properties: null
            holder_name: holder_name
          - country: ID
            code: code
            created: 2016-08-29T09:12:33.001Z
            description: description
            company: company
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            type: BANK_ACCOUNT
            properties: null
            holder_name: holder_name
          updated: 2016-08-29T09:12:33.001Z
          email: info@xendit.co
          status: null
        - individual_detail:
            place_of_birth: place_of_birth
            gender: MALE
            nationality: ID
            surname: surname
            date_of_birth: 2017-07-21
            surname_non_roman: surname_non_roman
            employment:
              nature_of_business: nature_of_business
              employer_name: employer_name
              role_description: role_description
            given_names: given_names
            given_names_non_roman: given_names_non_roman
            middle_name: middle_name
            mother_maiden_name: mother_maiden_name
          business_detail:
            business_name: business_name
            nature_of_business: nature_of_business
            business_type: CORPORATION
            date_of_registration: 2017-07-21
            business_domicile: ID
          addresses:
          - country: ""
            is_primary: true
            city: city
            created: 2016-08-29T09:12:33.001Z
            province_state: province_state
            street_line2: street_line2
            street_line1: street_line1
            meta: "{}"
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            category: category
            postal_code: postal_code
            updated: 2016-08-29T09:12:33.001Z
            status: null
          - country: ""
            is_primary: true
            city: city
            created: 2016-08-29T09:12:33.001Z
            province_state: province_state
            street_line2: street_line2
            street_line1: street_line1
            meta: "{}"
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            category: category
            postal_code: postal_code
            updated: 2016-08-29T09:12:33.001Z
            status: null
          metadata: "{}"
          reference_id: reference_id
          kyc_documents:
          - country: ""
            document_name: document_name
            document_number: document_number
            expires_at: expires_at
            sub_type: ""
            type: ""
            document_images:
            - document_images
            - document_images
            holder_name: holder_name
          - country: ""
            document_name: document_name
            document_number: document_number
            expires_at: expires_at
            sub_type: ""
            type: ""
            document_images:
            - document_images
            - document_images
            holder_name: holder_name
          created: 2016-08-29T09:12:33.001Z
          description: description
          type: INDIVIDUAL
          phone_number: +6281295412345
          id: id
          mobile_number: +6281295412345
          identity_accounts:
          - country: ID
            code: code
            created: 2016-08-29T09:12:33.001Z
            description: description
            company: company
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            type: BANK_ACCOUNT
            properties: null
            holder_name: holder_name
          - country: ID
            code: code
            created: 2016-08-29T09:12:33.001Z
            description: description
            company: company
            id: d290f1ee-6c54-4b01-90e6-d701748f0851
            type: BANK_ACCOUNT
            properties: null
            holder_name: holder_name
          updated: 2016-08-29T09:12:33.001Z
          email: info@xendit.co
          status: null
        has_more: true
      properties:
        has_more:
          type: boolean
        data:
          items:
            $ref: '#/components/schemas/Customer'
          type: array
      type: object
    getCustomerByReferenceID_400_response_allOf:
      properties:
        error_code:
          enum:
          - ENTITY_NOT_FOUND_ERROR
          - CLIENT_NOT_FOUND_ERROR
          - END_CUSTOMER_NOT_FOUND_ERROR
          - API_VALIDATION_ERROR
          example: ENTITY_NOT_FOUND_ERROR
          type: string
        message:
          example: Entity does not exist
      type: object
    getCustomerByReferenceID_400_response:
      allOf:
      - $ref: '#/components/schemas/Error'
      - $ref: '#/components/schemas/getCustomerByReferenceID_400_response_allOf'
    createCustomer_400_response_allOf:
      properties:
        error_code:
          enum:
          - DUPLICATE_END_CUSTOMER_ERROR
          - API_VALIDATION_ERROR
          example: DUPLICATE_END_CUSTOMER_ERROR
          type: string
        message:
          example: Client reference already exist
      type: object
    createCustomer_400_response:
      allOf:
      - $ref: '#/components/schemas/Error'
      - $ref: '#/components/schemas/createCustomer_400_response_allOf'
    updateCustomer_400_response_allOf:
      properties:
        error_code:
          enum:
          - ENTITY_NOT_FOUND_ERROR
          - CLIENT_NOT_FOUND_ERROR
          - END_CUSTOMER_NOT_FOUND_ERROR
          - DUPLICATE_END_CUSTOMER_ERROR
          - API_VALIDATION_ERROR
          example: ENTITY_NOT_FOUND_ERROR
          type: string
        message:
          example: Entity does not exist
      type: object
    updateCustomer_400_response:
      allOf:
      - $ref: '#/components/schemas/Error'
      - $ref: '#/components/schemas/updateCustomer_400_response_allOf'
    IdentityAccountResponse_properties:
      anyOf:
      - $ref: '#/components/schemas/AccountBank'
      - $ref: '#/components/schemas/AccountEwallet'
      - $ref: '#/components/schemas/AccountCard'
      - $ref: '#/components/schemas/AccountOTC'
      - $ref: '#/components/schemas/AccountQRCode'
      - $ref: '#/components/schemas/AccountPayLater'
    IdentityAccountRequest_properties:
      anyOf:
      - $ref: '#/components/schemas/AccountBank'
      - $ref: '#/components/schemas/AccountEwallet'
      - $ref: '#/components/schemas/AccountCard'
      - $ref: '#/components/schemas/AccountPayLater'
      - $ref: '#/components/schemas/AccountOTC'
      - $ref: '#/components/schemas/AccountQRCode'
x-owner: xendit
x-repositories:
- name: iluma-identity-service-v2
  branch: master
x-repositories-folder: docs/repositories
